#!/bin/bash

eval $(xwininfo -id $(xdotool getactivewindow) |
sed -n -e "s/^ \+Absolute upper-left X: \+\([0-9]\+\).*/x=\1/p" \
  -e "s/^ \+Absolute upper-left Y: \+\([0-9]\+\).*/y=\1/p" \
  -e "s/^ \+Width: \+\([0-9]\+\).*/w=\1/p" \
  -e "s/^ \+Height: \+\([0-9]\+\).*/h=\1/p" )

wmctrl -r :ACTIVE: -b remove,maximized_horz;
if [ $x -gt 3839 ]; then
  wmctrl -r :ACTIVE: -e 0,4800,0,957,1140
  wmctrl -r :ACTIVE: -b add,maximized_vert;
elif [ $x -gt 1919 ]; then
  wmctrl -r :ACTIVE: -e 0,2880,0,957,1140
  wmctrl -r :ACTIVE: -b add,maximized_vert;
else
  wmctrl -r :ACTIVE: -e 0,960,0,957,1140
  wmctrl -r :ACTIVE: -b add,maximized_vert;
fi
